#! /bin/bash

echo -------------------------------------
echo -------------------------------------

./runAstyle

echo -------------------------------------
echo -------------------------------------

./document

echo -------------------------------------
echo -------------------------------------

git add --all *
find . -name '.[a-z]*' -exec git add '{}' ';'
git commit --all --file=commitFile
git push
